codecov:
  bot: buildbot-dspc
fixes:
  - "::awe_manager/"
ignore:
  - "awe_manager/examples/"
  - '*/googletest/*'
  - '*/gtest/*'
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
