@startuml 3_behavioral_control
skinparam BoxPadding 15

box "AWE Service" #AAAFAA
participant "AWE Controller" as ctrl
participant "AWE-Manager" as awemgr #8888FF
end box
database "AWC\nDB" as awc

box "Audio Processors"
participant "Framework" as DSP #8888FF
participant "AWECore\nLib" as core #4444FF
end box

ctrl -> awemgr: awemgr_get_awc_context(mgr_p, endpoint)
note over awemgr: Gets AWC context\nfor endpoint
awemgr --> ctrl: awectx_p

ctrl -> awemgr: awemgr_control_write(awectx_p, "Mod.Var", data, ...)
awemgr <-[#blue]> DSP: tune command write
DSP <-> core: packetProcess()
awemgr --> ctrl: 

ctrl -> awemgr: awemgr_control_read(awectx_p, "Mod2.Var2", &response_buf)
awemgr <-[#blue]> DSP: tune command read
DSP <-> core: packetProcess()
awemgr --> ctrl: 
note over ctrl: consume\nresponse_buf

@enduml
